version: '2'
services:
  postgres_test:
    image: postgres:10
    environment:
     POSTGRES_PASSWORD: "admin"
     PGDATA: "/PG_DATA"
    container_name: postgres_test
    restart: unless-stopped
    volumes:
       - "/PG_DATA_TEST:/PG_DATA"
    ports:
        - "7474:5432"
