[app]
port = 8000
loglevel = 'INFO'
[parser]
delay = 60
url = 'https://news.ycombinator.com/newest'
[db]
#host = 'localhost' # для локального запуска
host = '' # ввести ip локальной машины
port = 7474
username = 'postgres'
password = 'admin'
name = 'postgres'
driver = 'postgres+psycopg2'